### ISSUE TITLE
Example show only one line

### ISSUE THREAD

**Issue by kraeml** [GrazerComputerClub/Blockly-gPIo#6]
I installed Blockly-gPIo on my Pi4. See the website and could connect to my Pi. But only one line output is shown:

```
Exekutiere Skript @pi4-home.local

Programm gestartet...
GC²'s Blockly Implementierung für Raspberry Pi
### Erledigt ###
```
Same with English language.

The output from `python3 run.py` is:

```
python3 run.py 
Adding flush statements after print calls...
Added flush lines.
CLI command: /usr/bin/python3 /opt/Blockly-gPIo/gpio.py
Sub process started  @ 2019-09-30 13:32:27.962121
Execution done
Adding flush statements after print calls...
Added flush lines.
CLI command: /usr/bin/python3 /opt/Blockly-gPIo/gpio.py
Sub process started  @ 2019-09-30 13:32:29.008142
Execution done
Adding flush statements after print calls...
Added flush lines.
CLI command: /usr/bin/python3 /opt/Blockly-gPIo/gpio.py
Sub process started  @ 2019-09-30 13:32:40.929958
Execution done
Adding flush statements after print calls...
Added flush lines.
CLI command: /usr/bin/python3 /opt/Blockly-gPIo/gpio.py
Sub process started  @ 2019-09-30 13:32:42.049617
Execution done
```

The content of `/opt/Blockly-gPIo/gpio.py` is:

```
cat gpio.py 
import sys
print("GC²'s Blockly Implementierung für Raspberry Pi")
sys.stdout.flush()

print('Wir haben ein paar Beispiele vorbereitet, welche von GitHub heruntergeladen werden können.')
sys.stdout.flush()

print('https://github.com/GrazerComputerClub/Blockly-gPIo/tree/master/examples')
```

Any idea where the last two lines are?

When I run as service:

```
cat  /etc/systemd/system/blockly-gpio.service 
[Unit]
Description=Blockly-gPIo server

[Service]
Type=simple
User=pi
WorkingDirectory=/opt/Blockly-gPIo/
ExecStart=/usr/bin/python3 /opt/Blockly-gPIo/run.py 
StandardOutput=syslog
StandardError=syslog

[Install]
WantedBy=multi-user.target
```
There were no output in /var/log/syslog.

**Comment by mstroh76** [comment]
We use this installation script (1 block):
https://github.com/GrazerComputerClub/Raspbian-Image-Generator/blob/master/stageA/03-install-services/00-run.sh

We use this systemd file:
https://github.com/GrazerComputerClub/Raspjamming-Image/blob/master/systemd/blockly-gpio.service

The Buster Raspbian Image was tested with Blockly-gPIo, but maybe a print error was not recognized. I will check asap.
Please check if you have an installation error.

**Comment by mstroh76** [comment]
The program must run at least for a few milliseconds so that the text is output.
With waiting 100 ms after print command, it works.
